import Link from 'next/link';
import { notFound, redirect } from 'next/navigation';
import { createClient } from '@/lib/supabase/server';

export default async function AttributionPage({ params }: { params: Promise<{ organizationId: string }> }) {
  const { organizationId } = await params; const supabase = await createClient(); const { data: { user } } = await supabase.auth.getUser(); if (!user) redirect('/');
  const { data: membership } = await supabase.from('organization_members').select('organizations(id,name)').eq('organization_id', organizationId).eq('user_id', user.id).maybeSingle(); if (!membership?.organizations) notFound(); const org = Array.isArray(membership.organizations) ? membership.organizations[0] : membership.organizations;
  const { data: rows } = await supabase.from('lead_attribution').select('kommo_lead_id,campaign_id,adset_id,ad_id,confidence,reason,attributed_at,manual_override').eq('organization_id', organizationId).order('attributed_at', { ascending: false }).limit(50);
  return <main className="shell"><aside className="sidebar"><div className="brand"><span className="brandMark">G</span><span>Dashboard Pronto</span></div><div className="workspace"><small>CLIENTE ATIVO</small><strong>{org.name}</strong><span>Atribuição</span></div><nav><Link href={`/app/${organizationId}`}>◈ <span>Visão geral</span></Link><Link className="active" href={`/app/${organizationId}/attribution`}>◎ <span>Atribuição</span></Link><Link href={`/app/${organizationId}/campaigns`}>▥ <span>Campanhas</span></Link><Link href={`/app/${organizationId}/leads`}>◌ <span>Leads</span></Link><Link href={`/app/${organizationId}/integrations`}>⌘ <span>Integrações</span></Link></nav><div className="sideBottom"><span className="statusDot"/> RLS multi-tenant ativo</div></aside><section className="content"><header><div><p className="eyebrow">ATTRIBUTION</p><h1>Atribuição<span>.</span></h1><p className="muted">Evidência consolidada exclusivamente para {org.name}.</p></div></header><article className="panel table"><div className="panelHead"><div><p className="kicker">LEAD ATTRIBUTION</p><h2>Últimas atribuições</h2><p className="muted">Modelo e confiança armazenados por lead.</p></div></div><div className="row head"><span>Lead</span><span>Campaign</span><span>Confiança</span><span>Modelo</span><span>Data</span></div>{(rows || []).map((row) => <div className="row" key={`${row.kommo_lead_id}-${row.attributed_at}`}><span>{row.kommo_lead_id}</span><span>{row.campaign_id || '—'}</span><span><em className={`confidence c${row.confidence}`}>{row.confidence}</em></span><span>{row.manual_override ? 'manual' : 'determinístico'}</span><span>{row.attributed_at ? new Date(row.attributed_at).toLocaleDateString('pt-BR') : '—'}</span></div>)}{!rows?.length && <div className="emptyState">Ainda não há atribuições para este cliente.</div>}</article></section></main>;
}
