import Link from 'next/link';
import { notFound, redirect } from 'next/navigation';
import { createClient } from '@/lib/supabase/server';

export default async function CampaignsPage({ params }: { params: Promise<{ organizationId: string }> }) {
  const { organizationId } = await params; const supabase = await createClient(); const { data: { user } } = await supabase.auth.getUser(); if (!user) redirect('/');
  const { data: membership } = await supabase.from('organization_members').select('organizations(id,name)').eq('organization_id', organizationId).eq('user_id', user.id).maybeSingle(); if (!membership?.organizations) notFound(); const org = Array.isArray(membership.organizations) ? membership.organizations[0] : membership.organizations;
  const { data: rows } = await supabase.from('meta_campaigns').select('campaign_id,name,objective,status,updated_at_meta').eq('organization_id', organizationId).order('updated_at_meta', { ascending: false }).limit(100);
  return <main className="shell"><aside className="sidebar"><div className="brand"><span className="brandMark">G</span><span>Dashboard Pronto</span></div><div className="workspace"><small>CLIENTE ATIVO</small><strong>{org.name}</strong><span>Campanhas Meta</span></div><nav><Link href={`/app/${organizationId}`}>◈ <span>Visão geral</span></Link><Link href={`/app/${organizationId}/attribution`}>◎ <span>Atribuição</span></Link><Link className="active" href={`/app/${organizationId}/campaigns`}>▥ <span>Campanhas</span></Link><Link href={`/app/${organizationId}/leads`}>◌ <span>Leads</span></Link><Link href={`/app/${organizationId}/integrations`}>⌘ <span>Integrações</span></Link></nav><div className="sideBottom"><span className="statusDot"/> RLS multi-tenant ativo</div></aside><section className="content"><header><div><p className="eyebrow">META ADS</p><h1>Campanhas<span>.</span></h1><p className="muted">Somente campanhas pertencentes ao ad account deste cliente.</p></div></header><article className="panel table"><div className="panelHead"><div><p className="kicker">CAMPAIGNS</p><h2>Inventário Meta</h2></div></div><div className="row head"><span>Campanha</span><span>ID</span><span>Objetivo</span><span>Status</span><span>Atualizada</span></div>{(rows || []).map((row) => <div className="row" key={row.campaign_id}><span className="campaignName">{row.name}<small>Meta Campaign</small></span><span>{row.campaign_id}</span><span>{row.objective || '—'}</span><span>{row.status || '—'}</span><span>{row.updated_at_meta ? new Date(row.updated_at_meta).toLocaleDateString('pt-BR') : '—'}</span></div>)}{!rows?.length && <div className="emptyState">Ainda não há campanhas sincronizadas para este cliente.</div>}</article></section></main>;
}
