import Link from 'next/link';
import { notFound, redirect } from 'next/navigation';
import { createClient } from '@/lib/supabase/server';

export default async function LeadsPage({ params }: { params: Promise<{ organizationId: string }> }) {
  const { organizationId } = await params; const supabase = await createClient(); const { data: { user } } = await supabase.auth.getUser(); if (!user) redirect('/');
  const { data: membership } = await supabase.from('organization_members').select('organizations(id,name)').eq('organization_id', organizationId).eq('user_id', user.id).maybeSingle(); if (!membership?.organizations) notFound(); const org = Array.isArray(membership.organizations) ? membership.organizations[0] : membership.organizations;
  const { data: rows } = await supabase.from('kommo_leads').select('kommo_lead_id,name,pipeline_id,status_id,price,responsible_user_id,created_at,updated_at,closed_at').eq('organization_id', organizationId).order('created_at', { ascending: false }).limit(100);
  return <main className="shell"><aside className="sidebar"><div className="brand"><span className="brandMark">G</span><span>Dashboard Pronto</span></div><div className="workspace"><small>CLIENTE ATIVO</small><strong>{org.name}</strong><span>Kommo / CRM</span></div><nav><Link href={`/app/${organizationId}`}>◈ <span>Visão geral</span></Link><Link href={`/app/${organizationId}/attribution`}>◎ <span>Atribuição</span></Link><Link href={`/app/${organizationId}/campaigns`}>▥ <span>Campanhas</span></Link><Link className="active" href={`/app/${organizationId}/leads`}>◌ <span>Leads</span></Link><Link href={`/app/${organizationId}/integrations`}>⌘ <span>Integrações</span></Link></nav><div className="sideBottom"><span className="statusDot"/> RLS multi-tenant ativo</div></aside><section className="content"><header><div><p className="eyebrow">KOMMO / CRM</p><h1>Leads<span>.</span></h1><p className="muted">Leads e estágios pertencentes exclusivamente a {org.name}.</p></div></header><article className="panel table"><div className="panelHead"><div><p className="kicker">PIPELINE</p><h2>Últimos leads</h2></div></div><div className="row head"><span>Lead</span><span>Pipeline</span><span>Stage</span><span>Valor</span><span>Criado</span></div>{(rows || []).map((row) => <div className="row" key={row.kommo_lead_id}><span className="campaignName">{row.name || row.kommo_lead_id}<small>Kommo ID · {row.kommo_lead_id}</small></span><span>{row.pipeline_id || '—'}</span><span>{row.status_id || '—'}</span><span>{row.price != null ? `R$ ${Number(row.price).toLocaleString('pt-BR')}` : '—'}</span><span>{row.created_at ? new Date(row.created_at).toLocaleDateString('pt-BR') : '—'}</span></div>)}{!rows?.length && <div className="emptyState">Ainda não há leads sincronizados para este cliente.</div>}</article></section></main>;
}
